apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fintechplatforms.platform.fintech.crossplane.io
  annotations:
    crossplane.io/xrd: "true"
spec:
  group: platform.fintech.crossplane.io
  names:
    kind: FintechPlatform
    listKind: FintechPlatformList
    plural: fintechplatforms
    singular: fintechplatform
    shortNames:
      - fp
      - fintech
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - platformName
                - environment
                - domain
                - awsConfig
                - networkConfig
                - databaseConfig
                - cacheConfig
                - monitoringConfig
                - securityConfig
              properties:
                platformName:
                  type: string
                  description: "Nome da plataforma fintech"
                  pattern: '^[a-z0-9-]+$'
                  minLength: 3
                  maxLength: 50
                environment:
                  type: string
                  description: "Ambiente da plataforma"
                  enum: ["development", "staging", "production"]
                domain:
                  type: string
                  description: "Domínio principal da plataforma"
                  pattern: '^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
                awsConfig:
                  type: object
                  required:
                    - region
                    - accountId
                  properties:
                    region:
                      type: string
                      description: "Região AWS para deploy"
                      enum: ["us-east-1", "us-west-2", "eu-west-1", "sa-east-1"]
                    accountId:
                      type: string
                      description: "ID da conta AWS"
                      pattern: '^[0-9]{12}$'
                    profile:
                      type: string
                      description: "Perfil AWS para uso"
                      default: "default"
                networkConfig:
                  type: object
                  required:
                    - vpcCidr
                    - publicSubnets
                    - privateSubnets
                    - databaseSubnets
                  properties:
                    vpcCidr:
                      type: string
                      description: "CIDR da VPC"
                      pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
                    publicSubnets:
                      type: array
                      minItems: 2
                      maxItems: 4
                      items:
                        type: object
                        required:
                          - cidr
                          - availabilityZone
                        properties:
                          cidr:
                            type: string
                            pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
                          availabilityZone:
                            type: string
                            pattern: '^[a-z]{2}-[a-z]+-[0-9]$'
                    privateSubnets:
                      type: array
                      minItems: 2
                      maxItems: 4
                      items:
                        type: object
                        required:
                          - cidr
                          - availabilityZone
                        properties:
                          cidr:
                            type: string
                            pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
                          availabilityZone:
                            type: string
                            pattern: '^[a-z]{2}-[a-z]+-[0-9]$'
                    databaseSubnets:
                      type: array
                      minItems: 2
                      maxItems: 4
                      items:
                        type: object
                        required:
                          - cidr
                          - availabilityZone
                        properties:
                          cidr:
                            type: string
                            pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
                          availabilityZone:
                            type: string
                            pattern: '^[a-z]{2}-[a-z]+-[0-9]$'
                databaseConfig:
                  type: object
                  required:
                    - engine
                    - engineVersion
                    - instanceClass
                    - storageGB
                    - multiAZ
                  properties:
                    engine:
                      type: string
                      enum: ["postgres", "mysql", "aurora-postgresql", "aurora-mysql"]
                    engineVersion:
                      type: string
                      description: "Versão do engine do banco"
                    instanceClass:
                      type: string
                      description: "Classe da instância RDS"
                      pattern: '^db\.[a-z0-9]+\.(large|xlarge|2xlarge|4xlarge|8xlarge|16xlarge|32xlarge)$'
                    storageGB:
                      type: integer
                      minimum: 20
                      maximum: 65536
                      description: "Storage em GB"
                    multiAZ:
                      type: boolean
                      description: "Habilitar Multi-AZ"
                    backupRetentionDays:
                      type: integer
                      minimum: 1
                      maximum: 35
                      default: 7
                    deletionProtection:
                      type: boolean
                      default: true
                cacheConfig:
                  type: object
                  required:
                    - engine
                    - engineVersion
                    - nodeType
                    - numCacheNodes
                    - multiAZ
                  properties:
                    engine:
                      type: string
                      enum: ["redis", "memcached"]
                    engineVersion:
                      type: string
                      description: "Versão do engine do cache"
                    nodeType:
                      type: string
                      description: "Tipo do nó de cache"
                      pattern: '^cache\.[a-z0-9]+\.(large|xlarge|2xlarge|4xlarge|8xlarge|16xlarge|32xlarge)$'
                    numCacheNodes:
                      type: integer
                      minimum: 1
                      maximum: 20
                    multiAZ:
                      type: boolean
                      description: "Habilitar Multi-AZ"
                monitoringConfig:
                  type: object
                  properties:
                    enablePrometheus:
                      type: boolean
                      default: true
                    enableGrafana:
                      type: boolean
                      default: true
                    enableELK:
                      type: boolean
                      default: true
                    enableJaeger:
                      type: boolean
                      default: true
                    prometheusRetentionDays:
                      type: integer
                      minimum: 1
                      maximum: 90
                      default: 15
                    elasticsearchStorageGB:
                      type: integer
                      minimum: 10
                      maximum: 1000
                      default: 100
                securityConfig:
                  type: object
                  properties:
                    enablePodSecurityStandards:
                      type: boolean
                      default: true
                    enableNetworkPolicies:
                      type: boolean
                      default: true
                    enableRBAC:
                      type: boolean
                      default: true
                    enableSSLTLS:
                      type: boolean
                      default: true
                    enableVulnerabilityScanning:
                      type: boolean
                      default: true
                scalingConfig:
                  type: object
                  properties:
                    hpaCPUTarget:
                      type: integer
                      minimum: 50
                      maximum: 90
                      default: 70
                    hpaMemoryTarget:
                      type: integer
                      minimum: 50
                      maximum: 90
                      default: 80
                    hpaMinReplicas:
                      type: integer
                      minimum: 1
                      maximum: 10
                      default: 2
                    hpaMaxReplicas:
                      type: integer
                      minimum: 5
                      maximum: 50
                      default: 20
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Platform
          type: string
          jsonPath: .spec.platformName
        - name: Environment
          type: string
          jsonPath: .spec.environment
        - name: Domain
          type: string
          jsonPath: .spec.domain
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
