apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  annotations:
    crossplane.io/package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0
  controllerConfigRef:
    name: helm-controller-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: helm-controller-config
spec:
  env:
    - name: HELM_DRIVER
      value: "configmap"
    - name: HELM_NAMESPACE
      value: "crossplane-system"
  serviceAccountName: crossplane-provider-helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-helm
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-provider-helm
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-provider-helm
subjects:
  - kind: ServiceAccount
    name: crossplane-provider-helm
    namespace: crossplane-system
